//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloWorld.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GreetingTbl
    {
        public string GreetingID { get; set; }
        public string GreetingText { get; set; }
    }
}
